
CREATE TABLE STUDENTS
(
	STUID INT,
	FIRSTNAME VARCHAR(25),
	LASTNAME VARCHAR(25),
	WEBSITE VARCHAR(50),
	CITY VARCHAR(25),
	DIVISION VARCHAR(20)
)
INSERT INTO STUDENTS
VALUES ('1011','KEYUR','PATEL','TECHONTHENET.COM','RAJKOT','II-BCX')
SELECT *FROM  STUDENTS


1.
	--PR_STUDENT_SELECTNAMESTARTLIKEK
	CREATE PROCEDURE PR_STUDENT_SELECTNAMESTARTLIKEK
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE FIRSTNAME LIKE 'K%'
	END

2.
	--PR_STUDENTS_SELECTFIRSTNAME
	CREATE PROCEDURE PR_STUDENTS_SELECTFIRSTNAME
	AS
	BEGIN
	SELECT FIRSTNAME FROM STUDENTS
	WHERE FIRSTNAME LIKE '_____'
	END

3.
	--PR_STUDENTS_SELECTFIRSTNAMELASTNAME
	CREATE PROCEDURE PR_STUDENTS_SELECTFIRSTNAMELASTNAME
	AS
	BEGIN
	SELECT FIRSTNAME,LASTNAME FROM STUDENTS
	WHERE CITY LIKE '%A' AND CITY LIKE '______'
	END

4.
	--PR_STUDENTS_SELECTLASTNAME
	CREATE PROCEDURE PR_STUDENTS_SELECTLASTNAME
	AS
	BEGIN
	SELECT LASTNAME FROM STUDENTS
	WHERE LASTNAME LIKE '%TEL'
	END

5. 
	--PR_STUDENTS_SELECTFIRSTNAMEHA
	CREATE PROCEDURE PR_STUDENTS_SELECTFIRSTNAMEHA
	AS
	BEGIN
	SELECT FIRSTNAME FROM STUDENTS
	WHERE FIRSTNAME LIKE 'HA%' AND FIRSTNAME LIKE '%T'
	END

6.
	--PR_STUDENTS_SELECTFIRSTNAME_K
	CREATE PROCEDURE PR_STUDENTS_SELECTFIRSTNAME_K
	AS
	BEGIN
	SELECT FIRSTNAME FROM STUDENTS
	WHERE FIRSTNAME LIKE 'K_Y%'
	END

7.
	--PR_STUDENTS_SELECTWEBSITE
	CREATE PROCEDURE PR_STUDENTS_SELECTWEBSITE
	AS
	BEGIN
	SELECT FIRSTNAME FROM STUDENTS
	WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'
	END

8.
	--PR_STUDENTS_SELECTLASTNAME_JER
	CREATE PROCEDURE PR_STUDENTS_SELECTLASTNAME_JER
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE LASTNAME LIKE '%JER%'
	END

9.
	--PR_STUDENTS_SELECTCITYNAME
	ALTER  PROCEDURE PR_STUDENTS_SELECTCITYNAME
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE CITY LIKE 'R%' AND CITY LIKE 'B%'
	END

10.
	--PR_STUDENTS_SELECTHAVINGWEBSITE
	CREATE PROCEDURE PR_STUDENTS_SELECTHAVINGWEBSITE
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE WEBSITE IS NOT NULL
	END

11.
	--PR_STUDENTS_SELECTFIRSTNAMEA
	CREATE PROCEDURE PR_STUDENTS_SELECTFIRSTNAMEA
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE FIRSTNAME LIKE '[A-H]%'
	END

12.
	--PR_STUDENTS_SELECTVOWEL
	CREATE PROCEDURE PR_STUDENTS_SELECTVOWEL
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE FIRSTNAME LIKE '_[AEIOU]%'
	END

13.
	--PR_STUDENTS_SELECTCITYROD
	CREATE PROCEDURE PR_STUDENTS_SELECTCITYROD
	AS
	BEGIN
	SELECT FIRSTNAME FROM STUDENTS
	WHERE CITY LIKE '%ROD%'
	END

14.
	--PR_SATUDENTS_SELECTWEBSITEBI
	CREATE PROCEDURE PR_SATUDENTS_SELECTWEBSITEBI
	AS
	BEGIN
	SELECT FIRSTNAME,LASTNAME FROM STUDENTS
	WHERE WEBSITE LIKE 'BI%'
	END

15.
	--PR_STUDENTS_SELECTLASTNAMESIX
	CREATE PROCEDURE PR_STUDENTS_SELECTLASTNAMESIX
	AS
	BEGIN
	SELECT LASTNAME FROM STUDENTS
	WHERE LASTNAME LIKE '______'
	END

16.
	--PR_STUDENTS_SELECTFIVE
	CREATE PROCEDURE PR_STUDENTS_SELECTFIVE
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE CITY LIKE '_____' AND CITY NOT LIKE 'BA%'
	END

17.
	--PR_STUDENTS_SELECTDIVISION
	CREATE PROCEDURE PR_STUDENTS_SELECTDIVISION
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE DIVISION LIKE 'II%'
	END

18.
	--PR_STUDENTS_SELECTDIVISIONNAME
	CREATE PROCEDURE PR_STUDENTS_SELECTDIVISIONNAME
	AS
	BEGIN
	SELECT FIRSTNAME FROM STUDENTS
	WHERE DIVISION LIKE '%BC%'
	END

19.
	--PR_STUDENTS_SELECTID
	CREATE PROCEDURE PR_STUDENTS_SELECTID
	AS
	BEGIN
	SELECT STUID,CITY FROM STUDENTS
	WHERE DIVISION LIKE '______' AND  WEBSITE IS NOT NULL
	END

20.
	--PR_STUDENTS_SELECTCONSONANT
	CREATE PROCEDURE PR_STUDENTS_SELECTCONSONANT
	AS
	BEGIN
	SELECT * FROM STUDENTS
	WHERE FIRSTNAME NOT LIKE '__[AEIOU]%'
	END