--1.
	--PR_PERSON_INFO_INSERT
	CREATE PROCEDURE PR_PERSON1_INSERT
	@PERSONID      INT,
	@PERSONNAME    VARCHAR(50),
	@SALARY        DECIMAL(8,2),
	@JOININGDATE   DATETIME,
	@CITY          VARCHAR(100),
	@AGE           INT,
	@BIRTHDATE     DATETIME
	AS
	BEGIN
	INSERT INTO PERSON1
	(
	 PERSONID ,
	 PERSONNAME ,
	 SALARY ,
	 JOININGDATE,
	 CITY ,
	 AGE ,
	 BIRTHDATE 
	)
	VALUES
	(
		@PERSONID ,
	    @PERSONNAME ,
	    @SALARY ,
	    @JOININGDATE,
	    @CITY ,
	    @AGE ,
	    @BIRTHDATE 
	)
	END
EXEC PR_PERSON1_INSERT 1,'KRISHA',20000,'2004-06-18','GONDAL',18, '2001-02-11'

------
	--PR_PERSON_INFO_UPDATE
	CREATE PROCEDURE PR_PERSON1_UPDATE
	@PERSONID      INT,
	@PERSONNAME    VARCHAR(50),
	@SALARY        DECIMAL(8,2),
	@JOININGDATE   DATETIME,
	@CITY          VARCHAR(100),
	@AGE           INT,
	@BIRTHDATE     DATETIME
	AS
	BEGIN
	UPDATE PERSON1
	SET 
	PERSONNAME =  @PERSONNAME ,   
	SALARY     =  @SALARY ,     
	JOININGDATE=  @JOININGDATE,   
	CITY       =  @CITY  ,     
	AGE        =  @AGE ,          
	BIRTHDATE  =  @BIRTHDATE     
	WHERE PERSONID= @PERSONID  
	END

EXEC PR_PERSON1_UPDATE 1,'KRISHNA',30000,'2004-06-18','RAJKOT',18, '2001-02-11'

------
	--PR_PERSON_INFO_DELETE
	CREATE PROCEDURE PR_PERSON1_DELETE
	@PERSONID INT
	AS
	BEGIN 
	DELETE FROM PERSON_INFO 
	WHERE PERSONID=@PERSONID  
	END
EXEC PR_PERSON1_DELETE 1 

--2.
	--INSERT--
	CREATE TRIGGER PERSONLOG1_INSERT
	ON PERSON1
	AFTER INSERT
	AS
	BEGIN
	DECLARE 
	@PERSONID    INT,
	@PERSONNAME  VARCHAR(250)
	SELECT PersonID = @PERSONID    FROM INSERTED
	SELECT PERSONNAME=@PERSONNAME FROM INSERTED
	INSERT INTO PERSONLOG
	VALUES ( @PERSONID,
			 @PERSONNAME,
			'INSERTED',
			 GETDATE()
			)
END	

INSERT INTO PERSON1 VALUES (4,'KRISHA',4000,'2020-09-02','GONDAL',18,'2000-02-02')
SELECT * FROM PERSONLOG

--UPDATE--
	ALTER TRIGGER PERSONLOG1_UPDATE
	ON PERSON
	AFTER UPDATE
	AS
	BEGIN
	DECLARE
	@PERSONID    INT,
	@PERSONNAME  VARCHAR(250)
	SELECT PersonID = @PERSONID    FROM INSERTED
	SELECT PERSONNAME=@PERSONNAME FROM INSERTED
	INSERT INTO PERSONLOG
	VALUES ( @PERSONID,
			 @PERSONNAME,
			'UPDATED',
			 GETDATE()
			)
END	
SELECT * FROM PERSONLOG

--DELETE--





--5--
CREATE TRIGGER TR_SETAGE
ON PERSON1
FOR INSERT 
AS
BEGIN
DECLARE @PERSONID INT,
	    @BIRTHDATE DATETIME
		SELECT @BIRTHDATE=BIRTHDATE FROM INSERTED
		SELECT @PERSONID=PERSONID FROM INSERTED
		UPDATE PERSON1 SET AGE=DATEDIFF(YEAR,@BIRTHDATE,GETDATE())
		WHERE @PERSONID=@PERSONID
END

--LAB2(4)--
CREATE PROCEDURE PR_ADD
	@SUB1 INT,
	@SUB2 INT,
	@TOTAL INT 
AS
BEGIN
	BEGIN TRY
	SET @TOTAL=@SUB1+@SUB2
	END TRY
	
	BEGIN CATCH
	SELECT ERROR_MESSAGE();
	END CATCH
END
EXEC PR_ADD 'KRISHA',20
EXEC PR_ADD 20,20





--EXAMPLE--
	create procedure pr_selectall
	@personname varchar(50),
	@age int
	as
	begin
	select  * from person1
	where personname like '%'+@personname+'%'
	or
	age=@age 
	end
