CREATE TABLE EMPLOYEES
(
	EID INT,
	ENAME VARCHAR(100),
	GENDER VARCHAR(10),
	JOININGDATE DATETIME,
	SALARY DECIMAL(8,2),
	CITY VARCHAR(100)
)
INSERT INTO EMPLOYEES VALUES (1,' Nick',' Male',' 01-JAN-13', 4000,' London')

INSERT INTO EMPLOYEES VALUES (2,' Julian',' Female',' 01-OCT-14', 3000,' New York')

INSERT INTO EMPLOYEES VALUES (3,' Roy',' Male',' 01-JUN-16', 3500,' London')

INSERT INTO EMPLOYEES VALUES(4,' Tom',' Male', NULL, 4500,' London')

INSERT INTO EMPLOYEES VALUES(5,' Jerry',' Male',' 01-FEB-13', 2800,' Sydney')

INSERT INTO EMPLOYEES VALUES(6,' Philip',' Male',' 01-JAN-15', 7000,' New York')

INSERT INTO EMPLOYEES VALUES(7,' Sara',' Female',' 01-AUG-17', 4800,' Sydney')

INSERT INTO EMPLOYEES VALUES(8,' Emily',' Female',' 01-JAN-15', 5500,' New York')

INSERT INTO EMPLOYEES VALUES(9,' Michael',' Male', NULL,6500,' London')


INSERT INTO EMPLOYEES VALUES (10,' John',' Male',' 01-JAN-15', 8800,' London')

SELECT * FROM EMPLOYEES

1.
	SELECT*FROM EMPLOYEES
	WHERE ENAME LIKE 'M__H%'

2.
	SELECT POWER(3,5) AS OUTPUT

3.
	SELECT GETDATE()-20

4.
	SELECT ENAME FROM EMPLOYEES
	WHERE ENAME LIKE 'J%' AND ENAME LIKE '%N%'

5.
	SELECT SUBSTRING ('SQL PROGRAMMING',2,9)

6.
	SELECT ENAME FROM EMPLOYEES
	WHERE CITY LIKE '%NEY' AND CITY LIKE '______'

7.
	SELECT CONVERT(VARCHAR,15)

8.
	ALTER  TABLE EMPLOYEES 
	ADD DEPARTMENT VARCHAR(20)

9.
	UPDATE EMPLOYEES
	SET DEPARTMENT = 'MARKETING'
	WHERE CITY = 'LONDON'

10.
	SELECT * FROM EMPLOYEES
	WHERE ENAME LIKE '%[N,Y]'

11.
	SELECT CEILING (63.1)
	SELECT CEILING(63.8)
	SELECT CEILING(-63.2)

12.
	SELECT * FROM EMPLOYEES
	WHERE JOININGDATE IS NULL

13.
	SELECT UPPER (ENAME) FROM EMPLOYEE
	SELECT LOWER (CITY) FROM EMPLOYEE

14.
	ALTER TABLE EMPLOYEES
	ALTER COLUMN ENAME CHAR(30)

15.
	SELECT MAX(SALARY) FROM EMPLOYEES
	GROUP BY CITY

16.
	SELECT ENAME+'WORKS AT'+CITY+'EARNS'+CAST(SALARY AS VARCHAR) FROM EMPLOYEES

17.
	SELECT COUNT(ENAME) FROM EMPLOYEES
	WHERE SALARY>5000

18.
	SELECT LEFT(ENAME,4), RIGHT(RTRIM(ENAME),3) FROM EMPLOYEES

19.
	SELECT SUM(SALARY),CITY FROM EMPLOYEES
	WHERE JOININGDATE>'2014-01-01'
	GROUP BY CITY
	HAVING SUM(SALARY)>15000

20.
	SELECT REPLACE(ENAME,'U','OO') FROM EMPLOYEES

21.
	SELECT AVG(SALARY),COUNT(ENAME),CITY
	FROM EMPLOYEES
	GROUP BY CITY

22.
	SELECT SUM(SALARY) AS TOTAL_SAL FROM EMPLOYEES
	WHERE GENDER='FEMALE'
	GROUP BY GENDER

23.
	SELECT DATEDIFF(YEAR,JOININGDATE,GETDATE()) FROM EMPLOYEES

24.
	ALTER TABLE EMPLOYEES DROP COLUMN DEPARTMENT

25.
	UPDATE EMPLOYEES SET CITY=NULL WHERE CITY='SYNDEY' 

26.
	SELECT ENAME, SALARY, JOININGDATE FROM EMPLOYEES

27.
	SELECT LEN(RTRIM(ENAME)+GENDER) FROM EMPLOYEES

28.
	SELECT MAX(SALARY) - MIN(SALARY) FROM EMPLOYEES

29.
	SP_RENAME 'EMPLOYEES.ENAME', 'FIRSTNAME'

30.
	SP_RENAME 'EMPLOYEES' , 'EMPMASTER'
















	



